server:
  port: 8081
  servlet:
    context-path: /lucymoney
limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元,最多要发${limit.maxMoney}元
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-674ckhta.bj.tencentcdb.com:10180/luckymoney
    username: root
    password: Brian@root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
